import { injectable, inject } from 'inversify'
import {
	Op,
	UniqueConstraintError,
	type CreationAttributes,
	type WhereOptions,
} from 'sequelize'
import Big from 'big.js'
import { IInvoiceService } from '../interfaces/service/IInvoiceService'
import { IInvoiceRepository } from '../interfaces/repository/IInvoiceRepository'
import { IInvoiceLineItemRepository } from '../interfaces/repository/IInvoiceLineItemRepository'
import { IProjectRepository } from '../interfaces/repository/IProjectRepository'
import { ICurrencyRepository } from '../interfaces/repository/ICurrencyRepository'
import { ITimesheetEntryRepository } from '../interfaces/repository/ITimesheetEntryRepository'
import { IProjectResourceAssignmentRepository } from '../interfaces/repository/IProjectResourceAssignmentRepository'
import { IRateCardRepository } from '../interfaces/repository/IRateCardRepository'
import { IExchangeRateRepository } from '../interfaces/repository/IExchangeRateRepository'
import { Invoice, INVOICE_STATUS, InvoiceStatus } from '../models/Invoice'
import { InvoiceLineItem } from '../models/InvoiceLineItem'
import { Project } from '../models/Project'
import { Currency } from '../models/Currency'
import { User } from '../models/User'
import { ResourceRoleType } from '../models/ResourceRoleType'
import { ProjectResourceAssignment } from '../models/ProjectResourceAssignment'
import { RateCard } from '../models/RateCard'
import { TimesheetEntry } from '../models/TimesheetEntry'
import { sequelize } from '../models'
import { TYPES } from '../containers/inversifyTypes'
import AppException from '../exceptions/AppException'
import { PaginationResult } from '../utils/Paginator'
import {
	GenerateInvoiceDTO,
	InvoiceDetailDTO,
	InvoiceFilterOptions,
	InvoiceGenerateResponseDTO,
	InvoiceLineItemResponseDTO,
	InvoiceListItemDTO,
	InvoiceStatusUpdateResponseDTO,
	InvoiceUpdateResponseDTO,
	UpdateInvoiceDTO,
} from '../types/invoiceTypes'

const INVOICE_LIST_INCLUDE = [
	{ model: Project, as: 'project', attributes: ['id', 'code', 'name'] },
	{ model: Currency, as: 'currency', attributes: ['id', 'code', 'symbol'] },
]

// Lightweight variant used by `updateInvoice` — only needs `lineItems.length`
// for `lineItemCount`, not the full nested user/resourceRoleType detail.
const INVOICE_SUMMARY_INCLUDE = [
	...INVOICE_LIST_INCLUDE,
	{ model: InvoiceLineItem, as: 'lineItems', attributes: ['id'] },
]

const INVOICE_DETAIL_INCLUDE = [
	{ model: Project, as: 'project', attributes: ['id', 'code', 'name'] },
	{ model: Currency, as: 'currency', attributes: ['id', 'code', 'symbol'] },
	{
		model: InvoiceLineItem,
		as: 'lineItems',
		include: [
			{ model: User, as: 'user', attributes: ['id', 'name'] },
			{
				model: ResourceRoleType,
				as: 'resourceRoleType',
				attributes: ['id', 'name'],
			},
		],
	},
]

interface ResolvedEntryContext {
	entry: TimesheetEntry
	user: User
	countryId: number
	assignment: ProjectResourceAssignment
}

@injectable()
export class InvoiceService implements IInvoiceService {
	constructor(
		@inject(TYPES.IInvoiceRepository)
		private invoiceRepository: IInvoiceRepository,
		@inject(TYPES.IInvoiceLineItemRepository)
		private invoiceLineItemRepository: IInvoiceLineItemRepository,
		@inject(TYPES.IProjectRepository)
		private projectRepository: IProjectRepository,
		@inject(TYPES.ICurrencyRepository)
		private currencyRepository: ICurrencyRepository,
		@inject(TYPES.ITimesheetEntryRepository)
		private timesheetEntryRepository: ITimesheetEntryRepository,
		@inject(TYPES.IProjectResourceAssignmentRepository)
		private projectResourceAssignmentRepository: IProjectResourceAssignmentRepository,
		@inject(TYPES.IRateCardRepository)
		private rateCardRepository: IRateCardRepository,
		@inject(TYPES.IExchangeRateRepository)
		private exchangeRateRepository: IExchangeRateRepository
	) {}

	/**
	 * Maps the DB-level unique-constraint backstops (either
	 * `invoices_active_project_billing_period_uidx`, for a race between two
	 * concurrent `GenerateInvoice` calls for the same project+period, or the
	 * plain unique constraint on `invoice_number`, in the vanishingly rare case
	 * of a collision in the sequential number generated by `nextInvoiceNumber`)
	 * to a clean 409 — same convention as `RateCardService.rethrowAsConflictIfUniqueConstraint`.
	 */
	private rethrowAsConflictIfUniqueConstraint(error: unknown): never {
		if (error instanceof UniqueConstraintError) {
			throw new AppException(
				'An invoice already exists for this project and billing period, or the generated invoice number is already in use — please retry',
				409
			)
		}
		throw error
	}

	private toListItemDTO(invoice: Invoice): InvoiceListItemDTO {
		const { project, currency } = invoice
		if (!project || !currency) {
			throw new AppException('Failed to load invoice details', 500)
		}
		return {
			id: invoice.id,
			invoiceNumber: invoice.invoiceNumber,
			project: { id: project.id, code: project.code, name: project.name },
			clientName: invoice.clientName,
			billingPeriodStart: invoice.billingPeriodStart,
			billingPeriodEnd: invoice.billingPeriodEnd,
			currency: { id: currency.id, code: currency.code, symbol: currency.symbol },
			totalAmount: Number(invoice.totalAmount),
			status: invoice.status,
			issuedDate: invoice.issuedDate,
			dueDate: invoice.dueDate,
		}
	}

	private toLineItemDTO(lineItem: InvoiceLineItem): InvoiceLineItemResponseDTO {
		const { user, resourceRoleType } = lineItem
		if (!user || !resourceRoleType) {
			throw new AppException('Failed to load invoice line item details', 500)
		}
		return {
			id: lineItem.id,
			user: { id: user.id, fullName: user.name },
			resourceRoleType: { id: resourceRoleType.id, name: resourceRoleType.name },
			timesheetEntryId: lineItem.timesheetEntryId,
			description: lineItem.description,
			hours: Number(lineItem.hours),
			unitRate: Number(lineItem.unitRate),
			amount: Number(lineItem.amount),
		}
	}

	private toDetailDTO(invoice: Invoice): InvoiceDetailDTO {
		const { project, currency, lineItems } = invoice
		if (!project || !currency || !lineItems) {
			throw new AppException('Failed to load invoice details', 500)
		}
		return {
			id: invoice.id,
			invoiceNumber: invoice.invoiceNumber,
			project: { id: project.id, code: project.code, name: project.name },
			clientName: invoice.clientName,
			clientEmail: invoice.clientEmail ?? null,
			billingPeriodStart: invoice.billingPeriodStart,
			billingPeriodEnd: invoice.billingPeriodEnd,
			currency: { id: currency.id, code: currency.code, symbol: currency.symbol },
			exchangeRate: Number(invoice.exchangeRate),
			subTotal: Number(invoice.subTotal),
			taxAmount: Number(invoice.taxAmount),
			totalAmount: Number(invoice.totalAmount),
			status: invoice.status,
			issuedDate: invoice.issuedDate,
			dueDate: invoice.dueDate,
			notes: invoice.notes ?? null,
			lineItems: lineItems.map((lineItem) => this.toLineItemDTO(lineItem)),
			createdAt: invoice.createdAt,
		}
	}

	/**
	 * `INV-{year}-{seq}`, sequential per calendar year of `issuedDate`.
	 * Application-level generation only — see `IInvoiceRepository.countByInvoiceNumberPrefix`'s
	 * doc-comment for why soft-deleted invoices are still counted, and
	 * `rethrowAsConflictIfUniqueConstraint` for the DB-level race backstop.
	 */
	private async nextInvoiceNumber(issuedDate: string): Promise<string> {
		const year = issuedDate.slice(0, 4)
		const prefix = `INV-${year}-`
		const existingCount =
			await this.invoiceRepository.countByInvoiceNumberPrefix(prefix)
		return `${prefix}${String(existingCount + 1).padStart(4, '0')}`
	}

	public async generateInvoice(
		data: GenerateInvoiceDTO
	): Promise<InvoiceGenerateResponseDTO> {
		const {
			projectId,
			billingPeriodStart,
			billingPeriodEnd,
			currencyId,
			issuedDate,
		} = data

		const project = await this.projectRepository.findByPk(projectId)
		if (!project) {
			throw new AppException('Project not found', 404)
		}

		const currency = await this.currencyRepository.findByPk(currencyId)
		if (!currency) {
			throw new AppException('Currency not found', 404)
		}

		// Application-level pre-check for the common case; see
		// `rethrowAsConflictIfUniqueConstraint`'s doc-comment for the DB-level
		// backstop against a concurrent request racing this check.
		const duplicate =
			await this.invoiceRepository.findActiveByProjectAndBillingPeriod(
				projectId,
				billingPeriodStart,
				billingPeriodEnd
			)
		if (duplicate) {
			throw new AppException(
				'An invoice already exists for this project and billing period',
				409
			)
		}

		// Only approved entries that have not already been billed onto another
		// invoice line item (`invoicedAt IS NULL`) are eligible — mirrors the
		// durable guard on `invoice_line_items.timesheet_entry_id` (see that
		// model's doc-comment).
		const entries = await this.timesheetEntryRepository.find({
			where: {
				projectId,
				isApproved: true,
				invoicedAt: null,
				entryDate: { [Op.between]: [billingPeriodStart, billingPeriodEnd] },
			},
			include: [{ model: User, as: 'user', attributes: ['id', 'name', 'countryId'] }],
			order: [
				['entryDate', 'ASC'],
				['id', 'ASC'],
			],
		})

		if (entries.length === 0) {
			throw new AppException(
				'No approved, un-invoiced timesheet entries were found for this project and billing period',
				400
			)
		}

		const baseCurrency = await this.currencyRepository.findActiveBaseCurrency()
		if (!baseCurrency) {
			throw new AppException(
				'No active base currency is configured; cannot resolve an exchange rate',
				500
			)
		}

		// "1 unit of base currency converts to `exchangeRateValue` units of
		// `currency`" — matches `invoices.exchange_rate`'s documented semantics
		// (see the `invoices` migration).
		let exchangeRateValue: Big
		if (currency.id === baseCurrency.id) {
			exchangeRateValue = new Big(1)
		} else {
			const rate = await this.exchangeRateRepository.findLatestActiveRate(
				baseCurrency.id,
				currency.id,
				issuedDate
			)
			if (!rate) {
				throw new AppException(
					`No active exchange rate found from ${baseCurrency.code} to ${currency.code}`,
					400
				)
			}
			exchangeRateValue = new Big(rate.rate)
		}

		// Batch-resolve every project resource assignment for the distinct users
		// in this billing period (one query total) rather than one lookup per
		// entry, to avoid an N+1 query pattern across a billing period that may
		// span many entries. All rows (active and historical/inactive) are
		// fetched — a user who changed role mid-period has more than one row
		// (see `ProjectResourceAssignmentService.assignResource`/`removeResource`'s
		// history-keeping model) and each entry must be billed at the role
		// effective on *that entry's own date*, not the user's current role.
		const distinctUserIds = Array.from(new Set(entries.map((entry) => entry.userId)))
		const assignments = await this.projectResourceAssignmentRepository.find({
			where: { projectId, userId: { [Op.in]: distinctUserIds } },
			order: [['assignedAt', 'DESC']],
		})
		const assignmentsByUserId = new Map<number, ProjectResourceAssignment[]>()
		for (const assignment of assignments) {
			const existing = assignmentsByUserId.get(assignment.userId)
			if (existing) {
				existing.push(assignment)
			} else {
				assignmentsByUserId.set(assignment.userId, [assignment])
			}
		}

		// Each user's list is already ordered DESC by assignedAt (the query
		// above is), so the first assignment whose `assignedAt` is on or before
		// the entry's date is the one effective on that date — same "pick
		// latest effective-as-of" logic as `resolveRateCard` below, applied to
		// assignments instead of rate cards.
		const resolveAssignment = (
			userId: number,
			asOfDate: string
		): ProjectResourceAssignment | undefined =>
			assignmentsByUserId
				.get(userId)
				?.find((assignment) => assignment.assignedAt.toISOString().slice(0, 10) <= asOfDate)

		const resolvedEntries: ResolvedEntryContext[] = entries.map((entry) => {
			const user = entry.user
			if (!user) {
				throw new AppException('Failed to load timesheet entry user', 500)
			}
			if (user.countryId === null) {
				throw new AppException(
					`User ${user.name} has no country configured; cannot determine a billing rate card`,
					400
				)
			}
			const assignment = resolveAssignment(entry.userId, entry.entryDate)
			if (!assignment) {
				throw new AppException(
					`No project resource assignment found for user ${user.name} effective on ${entry.entryDate}; cannot determine a billing rate`,
					400
				)
			}
			return { entry, user, countryId: user.countryId, assignment }
		})

		// Batch-resolve rate cards for every distinct (country, resourceRoleType)
		// pair in one query, then pick the effective card per entry date in
		// memory — same N+1-avoidance reasoning as the assignment lookup above.
		const pairs = new Map<string, { countryId: number; resourceRoleTypeId: number }>()
		for (const { countryId, assignment } of resolvedEntries) {
			const key = `${countryId}:${assignment.resourceRoleTypeId}`
			if (!pairs.has(key)) {
				pairs.set(key, { countryId, resourceRoleTypeId: assignment.resourceRoleTypeId })
			}
		}

		const rateCards =
			pairs.size > 0
				? await this.rateCardRepository.find({
						where: {
							isActive: true,
							[Op.or]: Array.from(pairs.values()).map((pair) => ({
								countryId: pair.countryId,
								resourceRoleTypeId: pair.resourceRoleTypeId,
							})),
						},
						order: [['effectiveDate', 'DESC']],
					})
				: []

		const rateCardsByPair = new Map<string, RateCard[]>()
		for (const rateCard of rateCards) {
			const key = `${rateCard.countryId}:${rateCard.resourceRoleTypeId}`
			const existing = rateCardsByPair.get(key)
			if (existing) {
				existing.push(rateCard)
			} else {
				rateCardsByPair.set(key, [rateCard])
			}
		}

		// `rateCardsByPair`'s lists are already ordered DESC by effectiveDate
		// (the query above is), so the first entry whose effectiveDate is on or
		// before `asOfDate` is the currently-effective one.
		const resolveRateCard = (
			countryId: number,
			resourceRoleTypeId: number,
			asOfDate: string
		): RateCard | undefined =>
			rateCardsByPair
				.get(`${countryId}:${resourceRoleTypeId}`)
				?.find((rateCard) => rateCard.effectiveDate <= asOfDate)

		let subTotal = new Big(0)
		const lineItemsData: Array<
			Omit<CreationAttributes<InvoiceLineItem>, 'invoiceId'>
		> = []

		for (const { entry, user, countryId, assignment } of resolvedEntries) {
			const rateCard = resolveRateCard(
				countryId,
				assignment.resourceRoleTypeId,
				entry.entryDate
			)
			if (!rateCard) {
				throw new AppException(
					`No effective rate card found for user ${user.name}'s country and resource role type as of ${entry.entryDate}`,
					400
				)
			}

			// Assumption (flagged for business sign-off — see the accompanying
			// report): rate cards are assumed to always be denominated in the
			// system's base currency, matching `invoices.exchange_rate`'s single
			// base-currency -> billing-currency conversion factor. A rate card in
			// any other currency would need a second, multi-hop conversion that
			// is not specified anywhere in the API contract, so it is rejected
			// explicitly here rather than silently mis-priced.
			if (rateCard.currencyId !== baseCurrency.id) {
				throw new AppException(
					`Rate card for user ${user.name} is denominated in a currency other than the base currency (${baseCurrency.code}); invoice generation does not support cross-currency rate cards`,
					400
				)
			}

			const unitRate = new Big(rateCard.billingRate).times(exchangeRateValue).round(2)
			const hours = new Big(entry.hours)
			const amount = unitRate.times(hours).round(2)
			subTotal = subTotal.plus(amount)

			lineItemsData.push({
				userId: user.id,
				resourceRoleTypeId: assignment.resourceRoleTypeId,
				timesheetEntryId: entry.id,
				description: entry.description,
				hours: hours.toFixed(2),
				unitRate: unitRate.toFixed(2),
				amount: amount.toFixed(2),
			})
		}

		// No tax computation rule is documented anywhere in the API spec (its
		// `GenerateInvoice` response example always shows `taxAmount: 0.00`) —
		// defaulted to zero here, flagged as an assumption requiring business
		// sign-off, same as `RateCardService.createRateCard`'s `costRate` default.
		const taxAmount = new Big(0)
		const totalAmount = subTotal.plus(taxAmount)

		const invoiceNumber = await this.nextInvoiceNumber(issuedDate)

		const invoice = await sequelize.transaction(async (transaction) => {
			let created: Invoice | undefined
			try {
				created = await this.invoiceRepository.create(
					{
						invoiceNumber,
						projectId,
						clientName: data.clientName,
						clientEmail: data.clientEmail ?? null,
						billingPeriodStart,
						billingPeriodEnd,
						currencyId,
						exchangeRate: exchangeRateValue.toFixed(6),
						subTotal: subTotal.toFixed(2),
						taxAmount: taxAmount.toFixed(2),
						totalAmount: totalAmount.toFixed(2),
						issuedDate,
						dueDate: data.dueDate,
						notes: data.notes ?? null,
					},
					{ transaction }
				)
			} catch (error) {
				this.rethrowAsConflictIfUniqueConstraint(error)
			}

			if (!created) {
				throw new AppException('Failed to create invoice', 500)
			}

			await this.invoiceLineItemRepository.bulkCreate(
				lineItemsData.map((lineItem) => ({ ...lineItem, invoiceId: created.id })),
				{ transaction }
			)

			await this.timesheetEntryRepository.update(
				{ invoicedAt: new Date() },
				{
					where: { id: { [Op.in]: entries.map((entry) => entry.id) } },
					returning: true,
					transaction,
				}
			)

			return created
		})

		return {
			id: invoice.id,
			invoiceNumber: invoice.invoiceNumber,
			projectId: project.id,
			projectName: project.name,
			clientName: invoice.clientName,
			billingPeriodStart: invoice.billingPeriodStart,
			billingPeriodEnd: invoice.billingPeriodEnd,
			currency: { id: currency.id, code: currency.code, symbol: currency.symbol },
			exchangeRate: Number(invoice.exchangeRate),
			subTotal: Number(invoice.subTotal),
			taxAmount: Number(invoice.taxAmount),
			totalAmount: Number(invoice.totalAmount),
			status: invoice.status,
			lineItemCount: lineItemsData.length,
		}
	}

	public async getAllInvoices(
		options: InvoiceFilterOptions
	): Promise<PaginationResult<InvoiceListItemDTO>> {
		const { projectId, status, startDate, endDate, currencyId, page, perPage } =
			options

		const whereClause: WhereOptions = {
			...(projectId !== undefined && { projectId }),
			...(status !== undefined && { status }),
			...(currencyId !== undefined && { currencyId }),
			...(startDate !== undefined && {
				billingPeriodStart: { [Op.gte]: startDate },
			}),
			...(endDate !== undefined && { billingPeriodEnd: { [Op.lte]: endDate } }),
		}

		const paginated = await this.invoiceRepository.findAndPaginate(page, perPage, {
			where: whereClause,
			include: INVOICE_LIST_INCLUDE,
			order: [
				['issuedDate', 'DESC'],
				['id', 'DESC'],
			],
		})

		return {
			...paginated,
			data: paginated.data.map((invoice) => this.toListItemDTO(invoice)),
		}
	}

	public async getInvoiceById(id: number): Promise<InvoiceDetailDTO> {
		const invoice = await this.invoiceRepository.findByPk(id, {
			include: INVOICE_DETAIL_INCLUDE,
			order: [[{ model: InvoiceLineItem, as: 'lineItems' }, 'id', 'ASC']],
		})

		if (!invoice) {
			throw new AppException('Invoice not found', 404)
		}

		return this.toDetailDTO(invoice)
	}

	public async getInvoiceForPdf(id: number): Promise<InvoiceDetailDTO> {
		return this.getInvoiceById(id)
	}

	public async updateInvoice(
		id: number,
		data: UpdateInvoiceDTO
	): Promise<InvoiceUpdateResponseDTO | null> {
		const invoice = await this.invoiceRepository.findByPk(id, {
			include: INVOICE_SUMMARY_INCLUDE,
		})
		if (!invoice) {
			return null
		}

		if (invoice.status !== INVOICE_STATUS.DRAFT) {
			throw new AppException('Only Draft invoices can be updated', 400)
		}

		// See `UpdateInvoiceDTO`'s doc-comment: rescaling already-materialised
		// line items on a currency change has no documented recalculation rule,
		// so it is rejected explicitly rather than guessed at. A `currencyId`
		// equal to the current one is accepted as a no-op.
		if (data.currencyId !== undefined && data.currencyId !== invoice.currencyId) {
			throw new AppException(
				"Changing an invoice's currency after generation is not supported; void or cancel this invoice and generate a new one in the desired currency instead",
				400
			)
		}

		const { project, currency, lineItems } = invoice
		if (!project || !currency || !lineItems) {
			throw new AppException('Failed to load invoice details', 500)
		}

		// `updateInvoiceSchema` only checks issuedDate <= dueDate when both are
		// supplied in the same request — a partial update touching only one of
		// the two must still be checked against the persisted value for the
		// other, same "defer cross-field ordering to the service for partial
		// updates" convention as `createProjectSchema`'s doc-comment.
		const nextIssuedDate = data.issuedDate ?? invoice.issuedDate
		const nextDueDate = data.dueDate ?? invoice.dueDate
		if (nextIssuedDate > nextDueDate) {
			throw new AppException('issuedDate must be on or before dueDate', 400)
		}

		const updated = await sequelize.transaction(async (transaction) => {
			return invoice.update(
				{
					...(data.clientName !== undefined && { clientName: data.clientName }),
					...(data.clientEmail !== undefined && { clientEmail: data.clientEmail }),
					...(data.issuedDate !== undefined && { issuedDate: data.issuedDate }),
					...(data.dueDate !== undefined && { dueDate: data.dueDate }),
					...(data.notes !== undefined && { notes: data.notes }),
				},
				{ transaction }
			)
		})

		return {
			id: updated.id,
			invoiceNumber: updated.invoiceNumber,
			projectId: project.id,
			projectName: project.name,
			clientName: updated.clientName,
			billingPeriodStart: updated.billingPeriodStart,
			billingPeriodEnd: updated.billingPeriodEnd,
			currency: { id: currency.id, code: currency.code, symbol: currency.symbol },
			exchangeRate: Number(updated.exchangeRate),
			subTotal: Number(updated.subTotal),
			taxAmount: Number(updated.taxAmount),
			totalAmount: Number(updated.totalAmount),
			status: updated.status,
			lineItemCount: lineItems.length,
		}
	}

	public async deleteInvoice(id: number): Promise<boolean> {
		const invoice = await this.invoiceRepository.findByPk(id, {
			include: [
				{
					model: InvoiceLineItem,
					as: 'lineItems',
					attributes: ['id', 'timesheetEntryId'],
				},
			],
		})
		if (!invoice) {
			return false
		}

		if (invoice.status !== INVOICE_STATUS.DRAFT) {
			throw new AppException('Only Draft invoices can be deleted', 400)
		}

		const timesheetEntryIds = (invoice.lineItems ?? []).map(
			(lineItem) => lineItem.timesheetEntryId
		)

		return sequelize.transaction(async (transaction) => {
			// Hard-delete the line items (no soft-delete of their own — see
			// `IInvoiceLineItemRepository.deleteByInvoiceId`'s doc-comment) before
			// freeing up the source timesheet entries, so the entries can be
			// picked up by a future `GenerateInvoice` call again.
			await this.invoiceLineItemRepository.deleteByInvoiceId(invoice.id, {
				transaction,
			})

			if (timesheetEntryIds.length > 0) {
				await this.timesheetEntryRepository.update(
					{ invoicedAt: null },
					{
						where: { id: { [Op.in]: timesheetEntryIds } },
						returning: true,
						transaction,
					}
				)
			}

			const deletedCount = await this.invoiceRepository.delete({
				where: { id },
				transaction,
			})
			return deletedCount > 0
		})
	}

	/**
	 * Shared status-transition helper backing `sendInvoice`/`markInvoicePaid`/
	 * `voidInvoice`/`cancelInvoice` — each is a guarded single-field `status`
	 * update, so factoring out the "load -> validate current status -> update"
	 * shape avoids repeating it four times.
	 */
	private async transitionStatus(
		id: number,
		allowedFromStatuses: ReadonlyArray<InvoiceStatus>,
		toStatus: InvoiceStatus,
		notAllowedMessage: string
	): Promise<InvoiceStatusUpdateResponseDTO> {
		const invoice = await this.invoiceRepository.findByPk(id)
		if (!invoice) {
			throw new AppException('Invoice not found', 404)
		}

		if (!allowedFromStatuses.includes(invoice.status)) {
			throw new AppException(notAllowedMessage, 400)
		}

		const updated = await sequelize.transaction(async (transaction) => {
			return invoice.update({ status: toStatus }, { transaction })
		})

		return { id: updated.id, status: updated.status }
	}

	public async sendInvoice(id: number): Promise<InvoiceStatusUpdateResponseDTO> {
		return this.transitionStatus(
			id,
			[INVOICE_STATUS.DRAFT],
			INVOICE_STATUS.SENT,
			'Only Draft invoices can be sent'
		)
	}

	public async markInvoicePaid(
		id: number
	): Promise<InvoiceStatusUpdateResponseDTO> {
		return this.transitionStatus(
			id,
			[INVOICE_STATUS.SENT],
			INVOICE_STATUS.PAID,
			'Only Sent invoices can be marked as paid'
		)
	}

	public async voidInvoice(id: number): Promise<InvoiceStatusUpdateResponseDTO> {
		return this.transitionStatus(
			id,
			[INVOICE_STATUS.DRAFT, INVOICE_STATUS.SENT],
			INVOICE_STATUS.VOID,
			'Only Draft or Sent invoices can be voided'
		)
	}

	public async cancelInvoice(
		id: number
	): Promise<InvoiceStatusUpdateResponseDTO> {
		return this.transitionStatus(
			id,
			[INVOICE_STATUS.DRAFT, INVOICE_STATUS.SENT],
			INVOICE_STATUS.CANCELLED,
			'Only Draft or Sent invoices can be cancelled'
		)
	}
}
